### ISSUE TITLE
Path issue when loading theme graphics

### ISSUE THREAD

**Issue by severoraz** [anthon38/refind-black#2]
I installed refind-black and the theme doesn't load because the theme.conf file omits the theme/ subdirectory preceding the icons'/backgrounds' path. This is an easy fix: either could the paths in the theme.conf file be modified, or the install path of refind-black be specified in the README.md

**Comment by anthon38** [comment]
I'm sorry but there is nothing in the specification (https://www.rodsbooks.com/refind/themes.html) that says themes should go in a themes/ folder. Even rodsmith doesn't use that scheme in his own theme. Please just adjust the theme.conf file to your setup.
